name = "Projector"
uuid = "abfb4c27-6a5b-4fca-8a0e-91ede93db49a"
authors = ["Thomas Burton <tburton5572@gmail.com>"]
version = "0.3.0"

[deps]
Fields = "54c0c897-3bff-4ba2-acae-d4c1acf2c14a"
PoissonSolver = "333ac5fb-9ca8-4109-ae2c-88ac1dd5ecab"

[extras]
ChebUtils = "5c307136-fb89-411d-b568-fbf16049e5ad"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ChebUtils"]
